optimizer: adam
coslr: true
coslrwarmup: true
criterions:
  PerformanceLoss:
    def_file: ./loss/SoftmaxLoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
model_dir: null
networks:
  classifier:
    def_file: ./models/DotProductClassifier.py
    optim_params: {lr: 0.01, betas: (0.9,0.999), eps: 1e-08}
    params: {dataset: inat, feat_dim: 1024}
  feat_model:
    def_file: ./models/reactnet.py
    fix: true
    optim_params: {lr: 0.01, betas: (0.9,0.999), eps: 1e-08}
    params: {}
shuffle: false
training_opt:
  backbone: reactnet
  batch_size: 16
  dataset: inat
  display_step: 10
  feature_dim: 1024
  log_dir: ./runs/DEFAULT/binary/softmax
  log_root: ./logs/inat
  num_classes: 8142
  num_epochs: 90
  num_workers: 12
  open_threshold: 0.1
  sampler: null
  scheduler_params: {gamma: 0.1, step_size: 3}
  stage: softmax_reactnet
  sub_dir: models
