optimizer: adam
coslr: true
criterions:
  PerformanceLoss:
    def_file: ./loss/BalancedSoftmaxLoss.py
    loss_params: {freq_path: None}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
model_dir: ./runs/DEFAULT/binary/softmax/adam/lr_0.01/
networks:
  classifier:
    def_file: ./models/DotProductClassifier.py
    optim_params: {lr: 0.01, betas: (0.9,0.999), eps: 1e-08}
    params: {feat_dim: 1024, num_classes: 100}
  feat_model:
    def_file: ./models/bxnet.py
    fix: true
    optim_params: {lr: 0.01, betas: (0.9,0.999), eps: 1e-08}
    params: {}
shuffle: false
training_opt:
  backbone: bxnet
  batch_size: 256
  dataset: DEFAULT
  display_step: 10
  feature_dim: 1024
  log_dir: ./runs/DEFAULT/clslearn/bxnet_decouple_balanced_softmax
  num_classes: 100
  num_iterations: 2000
  num_workers: 2
  open_threshold: 0.1
  sampler: {def_file: ./data/MetaSampler.py, type: MetaSampler, meta_batch_size: 1024, init_pow: 0.1, lr: 0.001}
  scheduler_params: {gamma: 0.1, step_size: 3}
  sub_dir: models
  imb_ratio: 0.1
