optimizer: sgd
coslr: true
criterions:
  PerformanceLoss:
    def_file: ./loss/SoftmaxLoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
model_dir: ./runs/DEFAULT/binary/softmax/adam/lr_0.01/
networks:
  classifier:
    def_file: ./models/TauNormClassifier.py
    optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
    params: {feat_dim: 1024, num_classes: 100}
  feat_model:
    def_file: ./models/bxnet.py
    fix: true
    optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
    params: {}
shuffle: false
training_opt:
  backbone: bxnet
  batch_size: 256
  dataset: DEFAULT
  display_step: 10
  feature_dim: 1024
  log_dir: ./runs/DEFAULT/clslearn/bxnet_tau_norm
  num_classes: 100
  num_epochs: 5
  num_workers: 2
  open_threshold: 0.1
  sampler: {def_file: ./data/ClassAwareSampler.py, num_samples_cls: 4, type: ClassAwareSampler}
  scheduler_params: {gamma: 0.1, step_size: 3}
  sub_dir: models
  imb_ratio: 0.1
