optimizer: adam
coslr: false
coslrwarmup: true
criterions:
  PerformanceLoss:
    def_file: ./loss/SoftmaxLoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
endlr: 0.0
warmup_iterations: 800
base_lr: 0.05
warmup_lr: 0.1
last: false
memory: {centroids: false, init_centroids: false}
model_dir: null
networks:
  classifier:
    def_file: ./models/DotProductClassifier.py
    optim_params: {lr: 0.05}
    params: {feat_dim: 1024, num_classes: 100}
  feat_model:
    def_file: ./models/reactnet.py
    fix: false
    optim_params: {lr: 0.05}
    params: {}
shuffle: false
training_opt:
  backbone: reactnet
  batch_size: 16
  dataset: DEFAULT
  display_step: 10
  feature_dim: 1024
  log_dir: ./logs/DEFAULT/binary/softmax_imba100
  num_classes: 100
  num_iterations: 13000
  num_workers: 0
  open_threshold: 0.1
  sampler: null
  scheduler_params: {gamma: 0.1, step_size: 3}
  sub_dir: models
  imb_ratio: 0.01